### ISSUE TITLE
Rust Compile Error

### ISSUE THREAD

**Issue by Jamiexhz** [genya0407/reing#4]
Error occurred when compiling. Logs attached as below:

```
Compiling rocket_contrib v0.4.2
error[E0463]: can't find crate for `notify`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_contrib-0.4.2/src/templates/fairing.rs:35:5
   |
35 |     extern crate notify;
   |     ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

```
Rust Version: rustc 1.43.0-nightly (158127853 2020-03-10)

**Comment by Jamiexhz** [comment]
Solved by configuring Cargo.toml.
```
image = "0.19.0"
notify = "4.0.12"
reing_text2image = { git = "https://github.com/genya0407/reing_text2image.git", rev = "0cfd7c650a552cf29fb011175e7fc1c62e2653ce" }
```

**Comment by Jamiexhz** [comment]
However, after installation, Reing didn't run as expected on the website which I defined in the .erc file earlier. Server showed that rocket service is running on localhost:8000. Do I need to take any further steps to make it deployed on a website?

**Comment by genya0407** [comment]
@Jamiexhz 

Thank you for feedback.

\> https://github.com/genya0407/reing/issues/4#issue-579081651

The compile error seems to due to compiler version. I could compile project by `rustc 1.43.0-nightly (7760cd0fb 2020-02-19)`.

\> https://github.com/genya0407/reing/issues/4#issuecomment-597542281

- What is `.erc` file?
- What does `Reing didn't run as expected on the website` mean?

Anyway, you can deploy Reing by following [README](https://github.com/genya0407/reing#how-to-develop). If you cannot deploy after following README, let me know more detailed situation.

**Comment by Jamiexhz** [comment]
> @Jamiexhz
> 
> Thank you for feedback.
> 
> > [#4 (comment)](https://github.com/genya0407/reing/issues/4#issue-579081651)
> 
> The compile error seems to due to compiler version. I could compile project by `rustc 1.43.0-nightly (7760cd0fb 2020-02-19)`.
> 
> > [#4 (comment)](https://github.com/genya0407/reing/issues/4#issuecomment-597542281)
> 
> * What is `.erc` file?
> * What does `Reing didn't run as expected on the website` mean?
> 
> Anyway, you can deploy Reing by following [README](https://github.com/genya0407/reing#how-to-develop). If you cannot deploy after following README, let me know more detailed situation.

Thank you for your kindly patience and reply.

* What is '.erc' file
Well, actually I was trying to say the '.env' file, but somehow I typed '.erc'……
Anyway, I followed the instructions here to modify the factors.  
[https://github.com/genya0407/reing#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B](url)
As the document is written in Japanese, I use the translator to help me understand the definitions. I assumed that 'APPLICATION_DOMAIN' is used to describe the domain related to the Reing service. 

* What does `Reing didn't run as expected on the website` mean?
Based on the assumptions, I thought that after defined domain in the .env file, the Reing services could run when I enter the website with the domain. I placed Reing documents and variables under /www/wwwroot/domain_name directory, ran the commands as instructed, but only to find an error when I entered with the domain.

I'm badly sorry for my poor knowledge on Rust. I'd be more than appreciated if you could give any possible instructions.

**Comment by genya0407** [comment]
Ah, sorry for lack of English documentation.

In order to launch Reing, you need to:

1. setup and launch PostgreSQL server.
2. copy [https://github.com/genya0407/reing/blob/master/.env.sample](.env.sample) to `.env`, and edit parameters
3. install [diesel_cli](https://github.com/diesel-rs/diesel/tree/master/diesel_cli) with PostgreSQL feature
4. migrate database by `DATABASE_URL='postgresql://username:password@127.0.0.1:5432/database-name' diesel migration run`
5. `cargo run`

then, you can access Reing at http://localhost:8000 .

**Comment by Jamiexhz** [comment]
> Ah, sorry for lack of English documentation.
> 
> In order to launch Reing, you need to:
> 
> 1. setup and launch PostgreSQL server.
> 2. copy [https://github.com/genya0407/reing/blob/master/.env.sample](.env.sample) to `.env`, and edit parameters
> 3. install [diesel_cli](https://github.com/diesel-rs/diesel/tree/master/diesel_cli) with PostgreSQL feature
> 4. migrate database by `DATABASE_URL='postgresql://username:password@127.0.0.1:5432/database-name' diesel migration run`
> 5. `cargo run`
> 
> then, you can access Reing at http://localhost:8000 .

Yeah, I ran commands as above, and Rocket service did tell me that the service is running at localhost:8000. Sorry for bothering you with these questions, but the thing is…… How can I manage to access the pages from the Internet, not just locally? Or say, how can I bind Reing service with a domain, so I can access the pages with the domain?

**Comment by genya0407** [comment]
I see.

APPLICATION_DOMAIN does not bind Reing to the Internet. It is used to embed answer links in notification emails.

You need to bind localhost:8000 to global IP address of your server using reverse proxy.
nginx is one of famous reverse proxies.

http://nginx.org/en/docs/beginners_guide.html#proxy

And you need to bind your global IP to domain name; buy domain and configure DNS server.

**Comment by Jamiexhz** [comment]
Thank you. My website is now online.

**Comment by genya0407** [comment]
:tada:
